init:
	terraform init --var-file=terraform.tfvars

plan:
	terraform plan --var-file=terraform.tfvars

apply:
	terraform apply --var-file=terraform.tfvars

destroy:
	terraform destroy --var-file=terraform.tfvars

output:
	terraform output
