#!/usr/bin/env bash
# Launch local web-chat against private Cloud Run remote-agent (direct URL, no proxy).
#
# OAuth credentials come only from terraform/terraform.tfvars → terraform apply → outputs.
# Process env is passed to Next.js; packages/web-chat/.env.local holds non-secret runtime config.
#
# Prerequisites:
#   terraform apply (web_oauth_client_id in terraform.tfvars)
#   ./scripts/deploy-agent.sh
#   gcloud auth login
#   gcloud auth application-default login
#   pnpm install
#
# Usage:
#   ./scripts/run-web-chat.sh              # launch
#   ./scripts/run-web-chat.sh --sync-env   # refresh .env.local runtime config from gcloud/terraform
#   ./scripts/run-web-chat.sh --force      # stop stale next dev on :3000, clear .next cache, then launch
#   ./scripts/setup-web-oauth.sh           # OAuth client setup guide

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

WEB_CHAT_ENV="${ROOT_DIR}/packages/web-chat/.env.local"
WEB_CHAT_NEXT="${ROOT_DIR}/packages/web-chat/.next"
SYNC_ENV=false
FORCE=false

for arg in "$@"; do
	case "${arg}" in
	--sync-env)
		SYNC_ENV=true
		;;
	--force)
		FORCE=true
		;;
	-h | --help)
		sed -n '2,18p' "$0"
		exit 0
		;;
	*)
		echo "Unknown option: ${arg} (try --help)" >&2
		exit 1
		;;
	esac
done

require_command pnpm
require_command gcloud
require_command terraform
require_gcloud_user_auth
require_gcloud_adc
validate_web_oauth_config

if [[ ! -d "${ROOT_DIR}/node_modules" ]]; then
	log "WARNING: node_modules not found. Run: pnpm install"
fi

resolve_runtime_var() {
	local key=$1
	local shell_var=$2
	local default_fn=$3
	local from_file=""

	if [[ -n ${!shell_var-} ]]; then
		printf '%s' "${!shell_var}"
		return 0
	fi

	if [[ ${SYNC_ENV} == false ]] && read_env_file_var "${WEB_CHAT_ENV}" "${key}" from_file; then
		printf '%s' "${from_file}"
		return 0
	fi

	"${default_fn}"
}

resolve_oauth_redirect_uri() {
	printf '%s' "${OAUTH_REDIRECT_URI:-http://localhost:3000/api/auth/callback}"
}

resolve_agent_url() {
	if [[ -n ${AGENT_URL-} ]] && ! looks_like_placeholder_agent_url "${AGENT_URL}"; then
		printf '%s' "${AGENT_URL}"
		return 0
	fi

	local url
	url="$(resolve_remote_agent_url)"
	if [[ -z ${url} ]]; then
		echo "remote-agent is not deployed in ${PROJECT_ID}/${REGION}. Run ./scripts/deploy-agent.sh first." >&2
		exit 1
	fi
	printf '%s' "${url}"
}

OAUTH_REDIRECT_URI="$(resolve_runtime_var OAUTH_REDIRECT_URI OAUTH_REDIRECT_URI resolve_oauth_redirect_uri)"
AGENT_URL="$(resolve_runtime_var AGENT_URL AGENT_URL resolve_agent_url)"

SESSION_SECRET="${SESSION_SECRET-}"
if [[ -z ${SESSION_SECRET} ]] && read_env_file_var "${WEB_CHAT_ENV}" SESSION_SECRET SESSION_SECRET; then
	:
elif [[ -z ${SESSION_SECRET} ]]; then
	SESSION_SECRET="$(openssl rand -base64 32)"
fi

GOOGLE_CLOUD_PROJECT="${GOOGLE_CLOUD_PROJECT:-${PROJECT_ID}}"
GOOGLE_CLOUD_LOCATION="${GOOGLE_CLOUD_LOCATION:-${REGION}}"

DELEGATION_JWT_EXCHANGE=false
if [[ -f "${ROOT_DIR}/.delegation-jwt-secret" ]]; then
	DELEGATION_JWT_EXCHANGE=true
fi

mkdir -p "$(dirname "${WEB_CHAT_ENV}")"
tmp_env="$(mktemp "${WEB_CHAT_ENV}.XXXXXX")"
trap 'rm -f "${tmp_env}"' EXIT

cat >"${tmp_env}" <<EOF
# Generated by scripts/run-web-chat.sh — runtime config only (OAuth from terraform outputs via process env)
OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
AGENT_URL=${AGENT_URL}
SESSION_SECRET=${SESSION_SECRET}
GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
DELEGATION_JWT_EXCHANGE=${DELEGATION_JWT_EXCHANGE}
EOF

mv "${tmp_env}" "${WEB_CHAT_ENV}"
trap - EXIT

WEB_CHAT_PORT="${WEB_CHAT_PORT:-3000}"

client_id_prefix="${GOOGLE_OAUTH_CLIENT_ID%%.*}"
log "OAuth from terraform (web_oauth_client_type=${WEB_OAUTH_CLIENT_TYPE})"
log "  client: ${client_id_prefix}…"
log "Wrote ${WEB_CHAT_ENV} (AGENT_URL, OAUTH_REDIRECT_URI, SESSION_SECRET, GCP project/location, DELEGATION_JWT_EXCHANGE)"
log "  AGENT_URL=${AGENT_URL}"
log "  Open http://localhost:${WEB_CHAT_PORT} after the dev server starts"
log "  If chat returns 403, ensure your email is in terraform allowed_emails (run.invoker)"

prepare_web_chat_dev_port "${WEB_CHAT_PORT}" "${FORCE}" "${WEB_CHAT_NEXT}"

warn_if_cloud_run_images_stale || true
case "${AGENT_URL}" in
https://*.run.app*)
	verify_remote_agent_api_catalog "${AGENT_URL}" || true
	;;
esac

cd "${ROOT_DIR}"
log "Building @agent-platform/agent-client (web-chat imports dist/)"
pnpm --filter @agent-platform/agent-client build

export OAUTH_REDIRECT_URI AGENT_URL SESSION_SECRET GOOGLE_CLOUD_PROJECT GOOGLE_CLOUD_LOCATION DELEGATION_JWT_EXCHANGE
exec pnpm --filter @agent-platform/web-chat exec next dev --port "${WEB_CHAT_PORT}"
